---

namespace: k8s-cleanup

serviceAccountName: k8s-cleanup-user
clusterRoleName: k8s-cluster-role
clusterRoleBinding: k8s-cleanup-clusterrolebinding


image:
  repository: abhijeetka/k8s-cleaner:v3
  pullPolicy: Always

# Runs every 6 hours
schedule: '0 */6 * * *'

failedJobsHistoryLimit: 6
successfulJobsHistoryLimit: 6


excludeNamespaces: "default,ingress-nginx,kube-node-lease,kube-public,kube-system"

maxDays: 3

podStatus: "Running, Succeeded, Failed, ContainerCreating, Error, CrashLoopBackOff"