kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ .Release.Name }}-role
rules:
  - apiGroups:
      - ""
    resources:
      - pods
      - namespaces
    verbs:
      - get
      - list
      - delete
      - watch
  - apiGroups:
      - apps
    resources:
      - replicasets
      - deployments
    verbs:
      - get
      - list
      - delete
      - watch